### PR TITLE
display end status text

### LINKED ISSUE #2: Enhancement: Display kyoku summary in the table of contents
## Description
In order to easily find kyoku user want to see, display the station summary in the table of contents.
Like the official Tenho app.

## Future Image
feature image

### PR DESCRIPTION
**Pull request by yuarasino**
## Issue
close #2 

### ロン・ツモ・流局 Sample
スクリーンショット 2020-03-11 22 12 50

### Double ロン Sample
スクリーンショット 2020-03-11 21 48 43

### CODE REVIEW

**Comment by Equim-chan** [comment]
In my environment, the title and the detail do not line up.

I think the solution is to add `line-height: 75%;` to `.kyoku-heading .end-status` to make it coordinated with `font-size: 75%;`

**Comment by yuarasino** [comment]
Since that method doesn't work in my environment, I look for an alternative method.
(Including changing the display location)

My environment:
Mac: chrome / firefox

**Comment by yuarasino** [comment]
It worked the same in my environment.
I will use that method.

My environment:
Mac chrome / firefox

スクリーンショット 2020-03-11 23 19 11

**Comment by Equim-chan** [comment]
I think I got it, by changing `<html>` to `<html lang="ja">`, I can produce the same result as yours.

**Pull request merged**
